on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  combine_pdfs:
    runs-on: ubuntu-latest
    name: Combine PDFs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PyPDF2
        run: pip install PyPDF2

      - name: Find PDF files
        id: findpdf
        run: |
          find . -name "Formula*.pdf" -type f > pdf_list.txt

      - name: Combine PDFs
        id: combine
        run: python combine_pdfs.py 

      - name: ls
        id: ls
        run: ls

      - uses: actions/checkout@v3
      - name: Commit PDF
        run: |
          git config --global user.name 'Amulya Jain'
          git config --global user.email 'amuhak@users.noreply.github.com'
          git commit -am "Automatic PDF combine"
          git push
        
      - name: Upload combined pdf
        uses: actions/upload-artifact@v2
        with:
          name: AllFormulaSheets
          path: AllFormulaSheets.pdf
      
