on:
  workflow_dispatch:

jobs:
  combine_pdfs:
    runs-on: ubuntu-latest
    name: Combine PDFs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PyPDF2
        run: pip install PyPDF2

      - name: Find PDF files
        id: findpdf
        run: |
          find . -name "Formula*.pdf" -type f > pdf_list.txt

      - name: Combine PDFs
        id: combine
        run: python combine_pdfs.py 

      - name: Upload combined pdf
        uses: actions/upload-artifact@v2
        with:
          name: AllFormulaSheets
          path: AllFormulaSheets.pdf
      
