on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  combine_pdfs:
    runs-on: ubuntu-latest
    name: Combine PDFs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PyPDF2
        run: pip install PyPDF2

      - name: Find PDF files
        id: findpdf
        run: |
          find . -name "Formula*.pdf" -type f > pdf_list.txt

      - name: Combine PDFs
        id: combine
        run: python combine_pdfs.py # Replace with the actual script/command to combine PDFs

      - name: Generate Unique Identifier
        id: generate_identifier
        run: echo "::set-output name=identifier::$(shasum combined.pdf | cut -c 1-40)"

      - name: Compare Identifiers
        id: compare_identifiers
        run: |
          LAST_RELEASE_IDENTIFIER=$(<last_release_identifier.txt)
          CURRENT_IDENTIFIER=${{ steps.generate_identifier.outputs.identifier }}

          if [ "$LAST_RELEASE_IDENTIFIER" == "$CURRENT_IDENTIFIER" ]; then
            echo "Combined PDF has not changed. Skipping release."
            exit 0
          fi

          echo $CURRENT_IDENTIFIER > last_release_identifier.txt

      - name: Upload combined pdf
        if: steps.compare_identifiers.outputs.result == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: combined-pdf
          path: combined.pdf

      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.compare_identifiers.outputs.result == 'success'
        with:
          files: combined.pdf
      
