on:
  push:
    paths:
      - pdf/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  combine_pdfs:
    runs-on: ubuntu-latest
    name: Combine PDFs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PyPDF2
        run: pip install PyPDF2

      - uses: actions/checkout@v3
      - name: Commit PDF
        run: |
          find . -name "Formula*.pdf" -type f > pdf_list.txt
          python combine_pdfs.py
          rm pdf_list.txt
          ls
          git config --global user.name 'Amulya Jain'
          git config --global user.email 'amuhak@users.noreply.github.com'
          git add AllFormulaSheets.pdf
          git commit -am "Automatic PDF combine"
          git push  
        
      - name: Combine PDFs
        id: combine
        run: |
          find . -name "Formula*.pdf" -type f > pdf_list.txt
          python combine_pdfs.py 
            
      - name: Upload combined pdf
        uses: actions/upload-artifact@v2
        with:
          name: AllFormulaSheets
          path: AllFormulaSheets.pdf
      
